### ISSUE TITLE
Typo: Lesson 4 Planning Search

### ISSUE THREAD

**Issue by gantners** [udacity/fcnd-issue-reports#105]
At 0:14 Typo in cc: You executed your first fight plan -> should be flight plan

**Comment by aurinalam** [comment]
Thank you for reporting. This issue is fixed.

https://classroom.udacity.com/nanodegrees/nd787/parts/5aa0a956-4418-4a41-846f-cb7ea63349b3/modules/0c12632a-b59a-41c1-9694-2b3508f47ce7/lessons/c9b7c43f-6c90-401a-a2ce-ac10613e34f1/concepts/129ac903-1864-47c1-80d3-fe079e924e68?contentVersion=1.0.0&contentLocale=en-us
