### ISSUE TITLE
medial axis exercise requires scikit-image package in environment

### ISSUE THREAD

**Issue by asimonov** [udacity/fcnd-issue-reports#111]

**Comment by jtuckerdunn** [comment]
Link to exercise: https://classroom.udacity.com/nanodegrees/nd787/parts/5aa0a956-4418-4a41-846f-cb7ea63349b3/modules/0c12632a-b59a-41c1-9694-2b3508f47ce7/lessons/5a623140-3e28-4ef1-a0f2-104715381c54/concepts/82275abd-86bc-43c0-a613-06728daffb22 Should we just add any dependencies that exist in jupyter notebook exercises to the fcnd environment so that students can use the notebooks outside of the workspace?

**Comment by ryan-keenan** [comment]
Added scikit-image to starterkit, thanks!

**Comment by asimonov** [comment]
This is exactly what i do — use notebooks locally

_____________________________
Kind Regards,
Alexey Simonov
