### ISSUE TITLE
Point containment test in Lecture 7.6 is incorrect

### ISSUE THREAD

**Issue by lnson** [udacity/fcnd-issue-reports#177]
Because the range of arccos is [0, pi], the theta computed at 3:16 is always positive. Therefore it doesn't help identify whether or not a point is inside or outside a polygon.

More info: https://udacity-flying-car.slack.com/archives/C919N6BA4/p1521563046000775

**Comment by ryan-keenan** [comment]
Thanks for reporting this! Turns out it's even more wrong than that.  As pointed out in another ticket, computing the dot product doesn't work for this because the result is always positive.  However, if you arrange the points in counterclockwise order and take the cross product between successive vectors you get positive values for positive angles and negative values for negative angles.  No need to compute the arccos. We ended up using the Python shapely package in the exercise so this section of the video didn't seem particularly relevant.  I have updated the video after removing the incorrect section.
