### ISSUE TITLE
2.10 QUIZ wrong answer

### ISSUE THREAD

**Issue by dambatenne** [udacity/fcnd-issue-reports#18]
Increase thrust on A and D while decreasing thrust by the same amount on B and C.
A and D rotate clockwise, so angular force related to them is counterclockwise. So the answer should be: Quad yaws counterclockwise as seen from above.

**Comment by 4FH** [comment]
Correct. Engine/propeller torque results in spin _opposite_ to rotational direction of propeller, at a lower rotational speed due to higher moment of inertia (assuming that the body of quad is heavier than propeller). Funny enough,  misconception in question somehow spread all over internet and found its way even to some university courses.

**Comment by ryan-keenan** [comment]
Great catch!  Thanks for reporting. Fixed now :)
